### ISSUE TITLE
[node] <defunct> after cluster

### ISSUE THREAD

**Issue by ceastman-ibm** [godaddy/node-cluster-service#82]
when i log into my pod running in kubernetes and check how many node processes are running:
ps -ef |grep node

i now see a fair amount of:
[node] <defunct>

what could be causing that? is that a code issue in our application cause the processes to go defunct? a couple of days ago i didnt see this behaviour.

i checked the health and info of cservice:

root@datalayer-7757f47d69-ft4x9:/home/node/app/node_modules/cluster-service/bin# ./cservice --accessKey .... info
cservice:  Running remote command: http://localhost:11987/cli?cmd=info&accessKey={ACCESS_KEY}
{ workers: { active: 16 },
  memory: { rss: 1753174016, heapTotal: 1109655552, heapUsed: 987398904 },
  net: 
   { connections: 113,
     connectionsOpen: 1,
     requests: 149,
     avgRequests: 0.5651043412921714,
     avgConnections: 0.23176924066212948 } }
root@datalayer-7757f47d69-ft4x9:/home/node/app/node_modules/cluster-service/bin# ./cservice --accessKey .... health
cservice:  Running remote command: http://localhost:11987/cli?cmd=health&accessKey={ACCESS_KEY}
'"OK"'
root@datalayer-7757f47d69-ft4x9:/home/node/app/node_modules/cluster-service/bin#

**Comment by asilvas** [comment]
Are you saying you see more than 17 node processes indicated by `cservice`? (1 master, 16 workers)

cservice is an abstraction atop the `cluster` api, so it's only reporting what it knows.

I'm assuming you have no other node apps running, so if you're seeing more `node` processes than the configured 17, it's possible they are artifacts of worker restarts. I've never seen this before since since old/bad workers are terminated, but I suppose it's possible. Might also be worth checking your `node -v`. Could be a bug.

1.

**Comment by tracker1** [comment]
@ceastman-ibm just curious why you would use node-cluster-service in addition to kubernetes, as opposed to just running more k8s managed instances tuned closer to raw needs?

**Comment by ceastman-ibm** [comment]
since nodejs is single threaded its only using 1 core out of the possible 16 that i have in my kubernetes worker nodes. so i figured i could get better utilization out of my worker nodes as opposed to creating more worker nodes that are underutilized.

**Comment by tracker1** [comment]
@ceastman-ibm, you can have more k8s workers... you're still launching N processes, but adding the complexity of a process manager inside another process manager.  if you had 16 k8s workers or 16 processes inside 1 worker, it's still 16 processes (actually only 15, since one is now only management process).  In addition to adding another (redundant) management process and a lot of unnecessary complexity in your system.

**Comment by asilvas** [comment]
Agreed, if you're already using k8s, cservice isn't providing a lot of benefit unless you have special feature needs (like proxy support versioning, remote control, etc). That aside, I'm still happy to help resolve the original issue.

**Comment by ceastman-ibm** [comment]
we are currently only running 6 worker nodes with 3 replicas of each microservice. we have roughly 70 microservices but they are all ui based microservices so no databases or any cpu intensive loads. but we do have some things that do have short bursts of cpu. so instead of adding more worker nodes (which costs more $) and increasing the replica count. i was investigating the node clustering service.

**Comment by tracker1** [comment]
I'm not sure about your billing for these services (billed per replica, assuming this means 3 workers in k8s?).  I was only pointing out that the number of processes would be the same whether it's 6 workers in a single k8s worker, or 6 k8s workers in cservice... and that growing/shrinking in k8s since you're using that anyways would be less complicated.  If you have other practical reasons, I can understand that.  If you don't have that much control over the k8s environment, your system may not be well balanced for processor utilization overall, but that's a secondary issue.

I do hope you (cestman) and asilvas are able to work through the issue.

**Comment by ceastman-ibm** [comment]
i was just thinking that since node js is single threaded its only using a maximum of 1 core in the k8s pod. Since the pod is running on a worker that has 16 cores, aren't those other 15 cores wasted?

so i was thinking that with cservice in that same k8s pod it would use all 16 cores if it needed to, as opposed to creating more pods in k8s.

**Comment by tracker1** [comment]
@ceastman-ibm gotcha...

FYI node itself will run multiple threads against a threadpool (for async i/o and other native modules that use it). The JS engine code executes in a single thread event loop.

16 single k8s pods would be less complicated, and probably balance the CPU usage on the server better.  Also, the overhead for node's cluster and messaging pipeline has a certain amount of overhead (so does load balancing/routing with k8s), that said you are already incurring the k8s cost, and node's message channels aren't *that* efficient.

Also, depending on your work load and bottlenecks, you may want to look at the new workers interface for node, which will run in isolated threads.

Aside: none of this is to take away from cservice, which is pretty nice... it's just if you're already using a process abstraction, creating layers of them just doesn't make sense to me.

**Comment by ceastman-ibm** [comment]
@tracker1 thanks for the clarification.
